[package]
name = "wind-dict"
version.workspace = true
edition.workspace = true

[dependencies]
wind-utils = { path = "../wind-utils" }
wind-candidate = { path = "../wind-candidate" }
wind-store = { path = "../wind-store" }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
memmap2 = "0.9"
serde = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
