import type { SearchEntry } from "@/schemas/searchEntry";

const tab = "hotkey";
const tabLabel = "按键";

// 与 HotkeyPage.vue 的 composerItems 保持同步：增删热键需同步增删此处条目
export const entries: SearchEntry[] = [
  // 中英文切换
  {
    id: "hotkeys.toggle_mode_keys",
    tab,
    tabLabel,
    card: "中英文切换",
    title: "切换按键",
    hint: "可多选，按下任意一个即切换",
    anchor: "hotkeys.toggle_mode_keys",
  },
  {
    id: "hotkeys.commit_on_switch",
    tab,
    tabLabel,
    card: "中英文切换",
    title: "切换时编码上屏",
    hint: "中文切换为英文时，将已输入的编码直接上屏",
    anchor: "hotkeys.commit_on_switch",
  },
  // 候选词管理
  {
    id: "hotkeys.pin_candidate",
    tab,
    tabLabel,
    card: "候选词管理",
    title: "置顶词条",
    hint: "将候选词固定到首位",
    anchor: "hotkeys.pin_candidate",
  },
  {
    id: "hotkeys.delete_candidate",
    tab,
    tabLabel,
    card: "候选词管理",
    title: "删除词条",
    hint: "隐藏候选词（单字不可删除）",
    anchor: "hotkeys.delete_candidate",
  },
  // 候选操作
  {
    id: "input.select_key_groups",
    tab,
    tabLabel,
    card: "候选操作",
    title: "次选/三选快捷键",
    hint: "选中第2、3位候选词的快捷键",
    anchor: "input.select_key_groups",
  },
  {
    id: "input.highlight_keys",
    tab,
    tabLabel,
    card: "候选操作",
    title: "高亮移动按键",
    hint: "在候选列表中移动选中项",
    anchor: "input.highlight_keys",
  },
  {
    id: "input.page_keys",
    tab,
    tabLabel,
    card: "候选操作",
    title: "翻页快捷键",
    hint: "同时启用多组翻页键",
    anchor: "input.page_keys",
  },
  {
    id: "input.select_char_keys",
    tab,
    tabLabel,
    card: "候选操作",
    title: "以词定字",
    hint: "输入词组后按指定键只取第1或第2个字",
    anchor: "input.select_char_keys",
  },
  // 功能快捷键
  {
    id: "hotkeys.switch_engine",
    tab,
    tabLabel,
    card: "功能快捷键",
    title: "切换输入方案",
    hint: "在已启用的输入方案间循环切换",
    anchor: "hotkeys.switch_engine",
  },
  {
    id: "hotkeys.toggle_full_width",
    tab,
    tabLabel,
    card: "功能快捷键",
    title: "切换全角/半角",
    hint: "切换字符宽度模式",
    anchor: "hotkeys.toggle_full_width",
  },
  {
    id: "hotkeys.toggle_punct",
    tab,
    tabLabel,
    card: "功能快捷键",
    title: "切换中/英文标点",
    hint: "切换标点符号类型",
    anchor: "hotkeys.toggle_punct",
  },
  {
    id: "hotkeys.toggle_toolbar",
    tab,
    tabLabel,
    card: "功能快捷键",
    title: "显示/隐藏状态栏",
    hint: "切换状态栏的显示状态",
    anchor: "hotkeys.toggle_toolbar",
  },
  {
    id: "hotkeys.open_settings",
    tab,
    tabLabel,
    card: "功能快捷键",
    title: "打开设置",
    hint: "打开设置窗口",
    anchor: "hotkeys.open_settings",
  },
  {
    id: "hotkeys.add_word",
    tab,
    tabLabel,
    card: "功能快捷键",
    title: "快捷加词",
    hint: "快速将输入的内容加入用户词库",
    anchor: "hotkeys.add_word",
  },
  {
    id: "hotkeys.toggle_s2t",
    tab,
    tabLabel,
    card: "功能快捷键",
    title: "切换简入繁出",
    hint: "开关简体输入→繁体输出（变体在「输入 → 简入繁出」中选择）",
    anchor: "hotkeys.toggle_s2t",
  },
  {
    id: "hotkeys.activate_ime",
    tab,
    tabLabel,
    card: "功能快捷键",
    title: "切换到本输入法",
    hint: "一键切换到本输入法",
    anchor: "hotkeys.activate_ime",
  },
  {
    id: "hotkeys.take_screenshot",
    tab,
    tabLabel,
    card: "功能快捷键",
    title: "输入法界面截图",
    hint: "保存当前可见的候选窗、工具栏、菜单等界面为图片文件",
    anchor: "hotkeys.take_screenshot",
  },
];
