// gen_pinyin_data 从 pinyin-data 原始数据生成 internal/tooltip/pinyin_data_generated.go
//
// 默认从 GitHub 下载所需文件；使用 -src 指定本地克隆目录可离线运行。
//
// 数据源：https://github.com/mozillazg/pinyin-data
// 数据源优先级（从高到低）：
//  1. overwrite.txt  — 手工纠正，最终权威（本地 -src 模式下可选）
//  2. kXHC1983.txt   — 现代新华字典多音字（排序以最常用音在前）
//  3. kTGHZ2013.txt  — 现代通用规范汉字多音字（补充 XHC 遗漏）
//  4. kMandarin_8105.txt — 8105 标准汉字首音（fallback）
//
// 刻意排除 kHanyuPinyin.txt（汉语大字典，含大量古音、方言音）
//
// 用法（在线，默认）：
//
//	go run ./cmd/gen_pinyin_data -out internal/tooltip/pinyin_data_generated.go
//
// 用法（离线，使用本地 pinyin-data 克隆）：
//
//	go run ./cmd/gen_pinyin_data -src /path/to/pinyin-data -out internal/tooltip/pinyin_data_generated.go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const githubBaseURL = "https://raw.githubusercontent.com/mozillazg/pinyin-data/"

func main() {
	src := flag.String("src", "", "pinyin-data 本地目录（留空时从 GitHub 下载）")
	ref := flag.String("ref", "master", "GitHub 分支/标签（仅 -src 为空时有效）")
	out := flag.String("out", "internal/tooltip/pinyin_data_generated.go", "输出 Go 文件路径")
	flag.Parse()

	dataDir := *src
	if dataDir == "" {
		// 在线模式：下载到临时目录
		tmp, err := os.MkdirTemp("", "pinyin-data-*")
		must(err, "创建临时目录")
		defer os.RemoveAll(tmp)
		dataDir = tmp

		base := githubBaseURL + *ref + "/"
		for _, name := range []string{"kXHC1983.txt", "kTGHZ2013.txt", "kMandarin_8105.txt"} {
			fmt.Fprintf(os.Stderr, "下载 %s ...\n", name)
			must(downloadFile(base+name, filepath.Join(tmp, name)), "下载 "+name)
		}
	}

	// 解析各来源文件
	xhc, err := parseFile(filepath.Join(dataDir, "kXHC1983.txt"))
	must(err, "kXHC1983.txt")
	tghz, err := parseFile(filepath.Join(dataDir, "kTGHZ2013.txt"))
	must(err, "kTGHZ2013.txt")
	m8105, err := parseFile(filepath.Join(dataDir, "kMandarin_8105.txt"))
	must(err, "kMandarin_8105.txt")
	overwrite, err := parseFileOptional(filepath.Join(dataDir, "overwrite.txt"))
	must(err, "overwrite.txt")

	// 为 8105 中每个字确定现代读音
	type entry struct {
		r        rune
		readings []string
	}
	var entries []entry

	for codeStr, primary := range m8105 {
		r := codeToRune(codeStr)

		var readings []string
		if ow, ok := overwrite[codeStr]; ok {
			readings = ow
		} else {
			seen := make(map[string]bool)
			for _, py := range xhc[codeStr] {
				if !seen[py] {
					seen[py] = true
					readings = append(readings, py)
				}
			}
			for _, py := range tghz[codeStr] {
				if !seen[py] {
					seen[py] = true
					readings = append(readings, py)
				}
			}
			if len(readings) == 0 {
				readings = primary
			}
		}

		entries = append(entries, entry{r: r, readings: readings})
	}

	// 按 Unicode 码位排序，保证生成文件稳定
	sort.Slice(entries, func(i, j int) bool { return entries[i].r < entries[j].r })

	// 输出统计
	polyCount := 0
	for _, e := range entries {
		if len(e.readings) > 1 {
			polyCount++
		}
	}
	fmt.Fprintf(os.Stderr, "生成: %d 个汉字，其中多音字 %d 个\n", len(entries), polyCount)

	// 写 Go 源文件
	f, err := os.Create(*out)
	must(err, "create output")
	defer f.Close()
	w := bufio.NewWriter(f)

	fmt.Fprintln(w, "// Code generated by cmd/gen_pinyin_data; DO NOT EDIT.")
	fmt.Fprintln(w, "// 数据源: pinyin-data (kXHC1983 + kTGHZ2013 + kMandarin_8105 + overwrite)")
	fmt.Fprintln(w, "// 已排除 kHanyuPinyin（汉语大字典古音）")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "package tooltip")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "// pinyinData 存储每个汉字的现代普通话读音（声调符号）。")
	fmt.Fprintln(w, "// 多音字按常用频率排序（最常用在前）。")
	fmt.Fprintln(w, "// 数据来源：kXHC1983（现代新华字典）+ kTGHZ2013（通用规范汉字）")
	fmt.Fprintln(w, "var pinyinData = map[rune][]string{")

	for _, e := range entries {
		quoted := make([]string, len(e.readings))
		for i, r := range e.readings {
			quoted[i] = fmt.Sprintf("%q", r)
		}
		fmt.Fprintf(w, "\t%q: {%s},\n", e.r, strings.Join(quoted, ", "))
	}

	fmt.Fprintln(w, "}")
	w.Flush()

	fmt.Fprintf(os.Stderr, "已写入: %s\n", *out)
}

// downloadFile 从 url 下载文件保存到 dst
func downloadFile(url, dst string) error {
	resp, err := http.Get(url) //nolint:gosec
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("HTTP %d: %s", resp.StatusCode, url)
	}
	f, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = io.Copy(f, resp.Body)
	return err
}

// parseFile 解析 pinyin-data 格式文件，返回 "U+XXXX" -> []string 映射
// 格式：U+XXXX: py1,py2  # 汉字
func parseFile(path string) (map[string][]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return parseReader(f)
}

// parseFileOptional 解析可选文件；文件不存在时返回空 map
func parseFileOptional(path string) (map[string][]string, error) {
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return map[string][]string{}, nil
	}
	return parseFile(path)
}

func parseReader(r io.Reader) (map[string][]string, error) {
	result := make(map[string][]string)
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if idx := strings.Index(line, "#"); idx >= 0 {
			line = strings.TrimSpace(line[:idx])
		}
		parts := strings.SplitN(line, ":", 2)
		if len(parts) != 2 {
			continue
		}
		code := strings.TrimSpace(parts[0])
		// 跳过非 BMP 字符（U+2XXXX 等）
		if len(code) > 6 {
			continue
		}
		rawPinyins := strings.Split(strings.TrimSpace(parts[1]), ",")
		var pinyins []string
		for _, py := range rawPinyins {
			py = strings.TrimSpace(py)
			if py != "" {
				pinyins = append(pinyins, py)
			}
		}
		if len(pinyins) > 0 {
			result[code] = pinyins
		}
	}
	return result, scanner.Err()
}

// codeToRune 将 "U+675C" 转为 rune
func codeToRune(code string) rune {
	code = strings.TrimPrefix(code, "U+")
	var n int32
	fmt.Sscanf(code, "%X", &n)
	return rune(n)
}

func must(err error, label string) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "错误 [%s]: %v\n", label, err)
		os.Exit(1)
	}
}
